### ISSUE TITLE
Change GraphQL endpoint to .env file

### ISSUE THREAD

**Issue by crimson-med** [crimson-med/react-prisma2-graphql-boilerplate#2]
Add a `.env` and `.env.local` file to the frontend. 

It should contain the GraphQL Endpoint used in `src/overmind/onInitialize.ts` and on `src/index.tsx`

**Comment by zg3d** [comment]
Hey, could I do this task?

**Comment by crimson-med** [comment]
@zg3d sure I'm that case please make sure to check contributing for the commit messages. Also make sure to update the quickstart section of the readme in frontend

**Comment by crimson-med** [comment]
Done with #c3b5a4e0a8d1f72ca6db4add7aac8e33349a2d5b
